# Generated by Django 6.1.1 on 2026-09-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_usercheckin_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterModelOptions(
            name='usercheckin',
            options={'verbose_name': 'User Check-in', 'verbose_name_plural': 'User Check-ins'},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('check_in', 'question')},
        ),
    ]
