# Generated by Django 6.1.1 on 2026-09-14 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0003_alter_useranswer_options_alter_usercheckin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='health_check.usercheckin')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='health_check.pattern')),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
                'ordering': ['id'],
            },
        ),
    ]
