# Generated by Django 6.1.1 on 2026-09-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_plan_user_plan_end_date_user_plan_lock_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_superuser', '-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
