# Generated by Django 6.1.1 on 2026-09-12 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('sleep_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('cycle', models.CharField(blank=True, max_length=10, null=True)),
                ('diet', models.CharField(blank=True, max_length=255, null=True)),
                ('mind_health', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Profile',
                'verbose_name_plural': 'Health Profiles',
            },
        ),
    ]
