# Generated by Django 6.1.1 on 2026-09-12 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_healthprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
