# Generated by Django 6.1.1 on 2026-09-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeUsageThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_check_questions', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Usage Threshold',
                'verbose_name_plural': 'Free Usage Thresholds',
                'ordering': ['id'],
            },
        ),
    ]
